# Generated by Django 2.2.4 on 2019-08-29 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drill_hole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='depthreading',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='depthreading',
            name='drill_hole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DepthReadings', to='drill_hole.DrillHole'),
        ),
    ]
