# Generated by Django 2.2.4 on 2019-09-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill_hole', '0002_auto_20190829_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drillhole',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='drillhole',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
