# Generated by Django 2.2.4 on 2019-09-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drill_hole', '0003_auto_20190904_0647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
